version: '2.20.3'

services:
  db:
    image: postgres:14.12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloudhaven-backend
    command: sh -c "
      /wait-for-it.sh db:5432 -- \
      python myproject/manage.py makemigrations && \
      python myproject/manage.py migrate --noinput && \
      python myproject/manage.py createsuperuser --noinput && \
      python myproject/manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./backend:/code
      - ./frontend/build/static:/code/myproject/frontend/public/static
      - django_static_volume:/code/myproject/static
      - django_media_volume:/code/myproject/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY_DJANGO=${SECRET_KEY_DJANGO}
      - CORS_ALLOWED_HOSTS=${CORS_ALLOWED_HOSTS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_TOKEN=${API_TOKEN}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data:
  django_static_volume:
  django_media_volume:
