@base = http://localhost:8000
@baseApiUrl = http://localhost:8000/api

# Аутентификация
POST {{base}}/api-token-auth/
Content-Type: application/json

{
  "username": "{{ env.DJANGO_USERNAME }}",
  "password": "{{ env.DJANGO_PASSWORD }}"
}

# Получение CSRF токена
GET {{base}}/api/csrf/

# Получение списка пользователей
GET {{baseApiUrl}}/users/
Authorization: Token {{ env.API_TOKEN }}

# Выход из системы
POST {{base}}/accounts/logout/
Content-Type: application/json
Authorization: Token {{ env.API_TOKEN }}

{
  "username": "{{ env.DJANGO_USERNAME }}"
}

# Создание пользователя
POST {{base}}/accounts/register/
Content-Type: application/json

{
  "username": "new_user",
  "email": "new_user@example.com",
  "first_name": "New",
  "last_name": "User",
  "password1": "newpassword",
  "password2": "newpassword"
}

# Получение списка файлов пользователя
GET {{baseApiUrl}}/storagefiles/by_user/
Authorization: Token {{ env.API_TOKEN }}

# Генерация короткой ссылки для файла
POST {{baseApiUrl}}/storagefiles/1/generate_short_link/
Content-Type: application/json
Authorization: Token {{ env.API_TOKEN }}
